// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/15/2026, 12:54:51 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/sterl/cipher-ai-rap-battle/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sterl/cipher-ai-rap-battle/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sterl/cipher-ai-rap-battle/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sterl/cipher-ai-rap-battle/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sterl/cipher-ai-rap-battle/frontend/plugins/**/*.{js,ts,mjs}","/home/sterl/cipher-ai-rap-battle/frontend/composables/**/*.{js,ts,mjs}","/home/sterl/cipher-ai-rap-battle/frontend/utils/**/*.{js,ts,mjs}","/home/sterl/cipher-ai-rap-battle/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sterl/cipher-ai-rap-battle/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/sterl/cipher-ai-rap-battle/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/sterl/cipher-ai-rap-battle/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;