// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai/battle-verse': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/battle-verse.post').default>>>>
    }
    '/api/ai/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/chat.post').default>>>>
    }
    '/api/ai/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/generate.post').default>>>>
    }
    '/api/ai/rhymes': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/rhymes.post').default>>>>
    }
    '/api/google/search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/search.post').default>>>>
    }
    '/api/supabase/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/supabase/health.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@3.21.2_@emnapi+c_a858d47e6aba5c1ab1f7c6ca18451c81/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}